# Generated by Django 5.1.5 on 2025-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
